
import Navbar from "@/components/Navbar";
import "./globals.css";
import 'tailwindcss/tailwind.css';



export const metadata = {
  title: "H's App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        <main className="container">
        {children}
        </main>
        </body>
    </html>
  );
}
