
import "./globals.css";
import 'tailwindcss/tailwind.css';



export const metadata = {
  title: "H's App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="container">{children}</body>
    </html>
  );
}
